### PR TITLE
Fixed bug when ignore the character input specified in the mask

### PR DESCRIPTION
**Pull request by newapx**
Example: mask: +7-999-999-99-99 ignored input character 7

### CODE REVIEW

**Comment by PeterStaev** [comment]
Hey @newapx , I do not understand what does this fix actually fixes. I've just tested on the demo with the mask that you provided and to me it looks like it works as expected.

**Comment by newapx** [comment]
I changed maskedtextfield.component.html with:
```
<ActionBar title="Demo" class="action-bar">
</ActionBar>
<StackLayout class="page">
    <MaskedTextField class="input input-border" mask="+7(999) 999-9999" [(ngModel)]="value" keyboardType="phone"></MaskedTextField>
</StackLayout>
```
And have bug: ignored input character 7. Platform **Android**.

**Comment by PeterStaev** [comment]
I still do not understand the problem. What do you mean by "ignored input character 7". The 7 is not a token so it is considered a hardcoded character similar to to the parenthesis and dashes. So user is not required to enter a 7. From what i see the value is correct and includes the 7 in it, see below:
image

**Comment by newapx** [comment]
I meant entering the number 7 from the keyboard into the position with the mask 9. Digit 7 is ignored.

image

**Comment by PeterStaev** [comment]
Thanks for your contribution! The changes are now on the new npm version.

**Pull request merged**
